// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ResponceInfo struct {
	Message string `json:"message"`
	Status  int    `json:"status"`
}

type Tweet struct {
	UID       string `json:"uid"`
	UserID    string `json:"userID"`
	Body      string `json:"body"`
	Image     string `json:"image"`
	CreatedAt string `json:"createdAt"`
}

type TweetInput struct {
	UserID string `json:"userID"`
	Body   string `json:"body"`
	Image  string `json:"image"`
}

type UpdateTweetInput struct {
	UID   string      `json:"uid"`
	Tweet *TweetInput `json:"tweet"`
}

type UpdateUserInput struct {
	UID  string     `json:"uid"`
	User *UserInput `json:"user"`
}

type User struct {
	UID       string `json:"uid"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Text      string `json:"text"`
	Avater    string `json:"avater"`
	Header    string `json:"header"`
	CreatedAt string `json:"createdAt"`
}

type UserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Text     string `json:"text"`
	Avater   string `json:"avater"`
	Header   string `json:"header"`
}
